name: CMake

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04]
        build-type: [Debug, Release]
    steps:
      - run: git config --global core.autocrlf false

      - uses: actions/checkout@v4.0.0

      - name: Build and Test
        shell: bash
        run: |
          # ...

          GENERATOR_FLAG=""
          if [ "$RUNNER_OS" == "Windows" ]; then
            GENERATOR_FLAG="-GNinja"
          fi

          cmake \
            -S svf_tools \
            -B .build \
            ${GENERATOR_FLAG} \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

          cmake --build .build
          ctest --test-dir .build
